GET http://localhost:5022/games

###

GET http://localhost:5022/games/3

###

POST http://localhost:5022/games
Content-Type: application/json

{
    "name": "The Test Game",
    "genreId": 1,
    "price": 60.55,
    "releaseDate": "2016-04-05"
}


###
PUT http://localhost:5022/games/2
Content-Type: application/json

{
   "name": "The Street Fighter 2 turbo",
    "genreId": 1,
    "price": 70.55,
    "releaseDate": "2016-04-05"
}   

###
DELETE http://localhost:5022/games/3
